### ISSUE TITLE
描述规范的建议：操作数的有无符号解释描述

### ISSUE THREAD

**Issue by x402** [ysyx-org/jemu-decoder#10]
RISC-V的寄存器操作数无论是按有符号还是无符号解释，长度都是`XLEN`，所以寄存器操作数不需要标注长度。
如RV32I，寄存器可以被解释为u32/s32。在RV64I中，32I作为64I的子集，指令是一样的，但寄存器操作数会被解释为u64/s64，而不是u32/s32。所以建议只标注u/s。如`u'rs1` `s'rs2`。
RISC-V中立即数都是符号位扩展，所以不需要给立即数标注是按有符号还是无符号解释。同样立即数的符号扩展也是扩展至`XLEN`长度。
建议可以用[11:0]这样的格式表示位选择，用SEXT(x)表示x的有符号扩展。

示例：
BGE
```
mask: '-----------------101-----1100011'

args:
  rs2: 24:20
  rs1: 19:15
  imm: [8:11, 25:30, 7, 31]

exec:
  pc: "s'rs1 >= s'rs2 ? pc + imm : pc + 4"

meta:
  encoding: S
  importance: NaN
```
![bge](https://user-images.githubusercontent.com/75256484/179358375-cc51f164-cc63-44b7-928d-cb5acefc2fc9.png)

BGEU
```
mask: '-----------------111-----1100011'

args:
  rs2: 24:20
  rs1: 19:15
  imm: [8:11, 25:30, 7, 31]

exec:
  pc: "u'rs1 >= u'rs2 ? pc + imm : pc + 4"

meta:
  encoding: S
  importance: NaN
```
![bgeu](https://user-images.githubusercontent.com/75256484/179358402-76327f7c-ff25-4a2f-b369-bf106efc6afd.png)

ADDIW
```
mask: '-----------------000-----0011011'

args:
  rs1: 19:15
  rd: 11:7
  imm: 31:20

exec:
  rd: "SEXT((rs1 + imm)[31:0])"

meta:
  encoding: I
  importance: NaN
```
![addiw](https://user-images.githubusercontent.com/75256484/179358826-3ff6b470-8dbd-489e-a796-4d7273f66c7a.png)
